### ISSUE TITLE
QEMU pseudo encodings

### ISSUE THREAD

**Issue by ayunami2000** [filipecbmoc/vnc-rfb-client#5]
Hello,

Is it possible to add support for QEMU audio pseudo encoding and (higher priority) QEMU relative pointer motion pseudo encoding?

https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#777qemu-pointer-motion-change-pseudo-encoding

I created a similar issue over on the more popular node-rfb2 GitHub page, but I don't know how to implement it myself and the project developer is not available to implement it.

Even if you are only able to help me implement it myself, it would be greatly appreciated!

**Comment by ayunami2000** [comment]
Update, I managed to implement them both using your repository as a base. If you want me to create a pull request let me know: https://github.com/ayunami2000/vnc-rfb-client

**Comment by filipecbmoc** [comment]
Hello,

It would be great. Please create de pull request.

Thanks.

Atts,
Filipe Calaça Barbosa

**Comment by ayunami2000** [comment]
#6
